seed : 1
result_dir: results
env:
  name: your_train_envirionment_name
ffc:
  loop: 1
  nums: 2
train:
  w: 1.0
  loss_ratio: 
    - 1
    - 1
    - 1
  perceptual:
    net : 'vgg16'
    style:
      - '3'
      - '8'
      - '15'
    content:
      - '8'
  mask: True
  model: unet_fal
  epoch: 1000
  batch: 4
  num_workers: 4
  init_weight: null
  input_kernel:
    - 15

sched:
  name: steplr
  init_lr: 1.0e-3
  lr_max: 5.0e-3
  cawr2:
    t0: 1
    tmul: 1
    tup: 0.05
    gamma: 0.6
  cawr:
    t0: 1.0
    tmul: 1
    tup: 0
    gamma: 0.2
  steplr_multi:
    milestones:
      - 1500
      - 2000
      - 4000
    gamma: 0.5

opt:
  name: AdamW
  wd: 0

dataset:
  name: your/data/path/Dense_Haze
  in_size:
    - 1024
    - 1024
  train:
    hazy : your/data/path
    gt : your/gt/path
  val:
    name : Dense_Haze
    hazy : your/data/path
    gt : your/gt/path
  test:
    name : Dense_Haze
    hazy : your/data/path
    gt : your/gt/path
val :
  mask: False
test :
  mask: False